# Generated by Django 4.2.6 on 2024-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0002_remove_customuser_age_remove_foodmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='calories',
            field=models.FloatField(null=True),
        ),
    ]
