# Generated by Django 4.2.6 on 2024-06-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0003_alter_foodmodel_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedcalories',
            name='calorie_consumed',
            field=models.FloatField(default=0),
        ),
    ]
