# Generated by Django 4.2.6 on 2024-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0004_alter_consumedcalories_calorie_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumedcalories',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
