# Generated by Django 4.2.6 on 2024-06-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0005_consumedcalories_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumedcalories',
            name='total_calorie_consumed',
            field=models.FloatField(default=0),
        ),
    ]
